### ISSUE TITLE
ownership for asa driver

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation-community/napalm-asa#6]
Hello,
community drivers are going to be maintained by the community or considered deprecated and unmaintained. For that reason we are looking for people willing to maintain this repo. Owners will have full admin rights on this repo and on its pypy package.

Pinging top contributors to see if they are interested; @DiogoAndre @ogenstad

If you have questions/comments let me know.

Regards

**Comment by DiogoAndre** [comment]
Hi @dbarrosop. I'm happy to try and pick this up again. Couldn't follow up the work early in 2017 and hope to catch up now. Thanks!

**Comment by dbarrosop** [comment]
I have invited you to manage this repo.

**Comment by enzzzy** [comment]
Hi  @DiogoAndre,
Are you still working on this driver? 
I have some use cases for this driver and would like to offer some help. 
For example: Python3 support would be one of the things, that I can immediately start to work on.

**Comment by dbarrosop** [comment]
Not sure if the project is abandoned. @DiogoAndre can you confirm? @enzzzy would you like to take ownership if it is?

**Comment by enzzzy** [comment]
Not sure, but I can definately contribute some work as I need to get this driver into a state that I can work with it. (Current open issue, python3 support, pip 10.0.1 installation issue, ...)

**Comment by ktbyers** [comment]
PIP installation issue is an easy fix.

PY3 support though is probably a lot of work. Someone will have to sign-up to do the work for that.

**Comment by enzzzy** [comment]
I'm willing to sing-up for that work. 
Would it be ok to swap out urllib2 for the requests library?

**Comment by dbarrosop** [comment]
Totally. However, if @DiogoAndre is not up to the task either you or someone else will have to take care of this community driver.

**Comment by DiogoAndre** [comment]
Hi all, let’s get this thing off the ground! Thanks for stepping up @enzzzy.  I will finally have a lot of free time starting Monday and will be happy to work together to make this driver a lot more functional.

**Comment by DiogoAndre** [comment]
Going to close this one and will start working in the issues discussed here (#7 and #8)
